import { useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, RotateCcw, Square, CheckSquare } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';

type Stage = 'survey' | 'installation';
type Props = { stage:Stage; shopId:string; surveyId?:string; jobId?:string; assignedTo?:string; readOnly?:boolean };
type Row = { key:string; entityType:'measurement'|'survey_photo'|'work_item'|'installation_photo'; entityId:string; workItemId?:string; title:string; subtitle?:string; image?:string };

export function ItemLevelReviewPanel({stage,shopId,surveyId,jobId,assignedTo,readOnly=false}:Props){
 const {profile}=useAuth(); const qc=useQueryClient(); const [selected,setSelected]=useState<Set<string>>(new Set()); const [note,setNote]=useState(''); const [busy,setBusy]=useState(false); const [err,setErr]=useState('');
 const {data:items=[]}=useQuery({queryKey:['item-review-items',shopId,surveyId],queryFn:async()=>{let q=supabase.from('work_items').select('id,work_type_name,survey_width,survey_height,survey_unit,survey_quantity,survey_area,approved_width,approved_height,approved_unit,approved_quantity,approved_area').eq('shop_id',shopId).order('created_at'); if(surveyId) q=q.eq('survey_id',surveyId); const {data,error}=await q;if(error)throw error;return data||[];},enabled:!!shopId});
 const {data:photos=[]}=useQuery({queryKey:['item-review-photos',stage,surveyId,jobId],queryFn:async()=>{if(stage==='survey'){const {data,error}=await supabase.from('survey_photos').select('id,photo_url,caption').eq('survey_id',surveyId!).order('created_at');if(error)throw error;return data||[];}const {data,error}=await supabase.from('installation_proofs').select('id,photo_url,angle,work_item_id').eq('installation_job_id',jobId!).order('captured_at');if(error)throw error;return data||[];},enabled:stage==='survey'?!!surveyId:!!jobId});
 const {data:decisions=[]}=useQuery({queryKey:['item-review-decisions',stage,surveyId,jobId],queryFn:async()=>{let q=supabase.from('field_review_decisions').select('*').eq('stage',stage); q=stage==='survey'?q.eq('survey_id',surveyId!):q.eq('installation_job_id',jobId!);const {data,error}=await q;if(error&&/field_review_decisions|schema cache/i.test(error.message||''))return [];if(error)throw error;return data||[];},enabled:stage==='survey'?!!surveyId:!!jobId});
 const rows:Row[]=useMemo(()=>{const a:Row[]=[]; for(const it of items as any[]){const w=stage==='survey'?it.survey_width:it.approved_width??it.survey_width,h=stage==='survey'?it.survey_height:it.approved_height??it.survey_height,u=stage==='survey'?it.survey_unit:it.approved_unit??it.survey_unit,q=stage==='survey'?it.survey_quantity:it.approved_quantity??it.survey_quantity,ar=stage==='survey'?it.survey_area:it.approved_area??it.survey_area;a.push({key:`item:${it.id}`,entityType:stage==='survey'?'measurement':'work_item',entityId:it.id,workItemId:it.id,title:it.work_type_name||'Work Item',subtitle:`${w??'—'} × ${h??'—'} ${u||''} · Qty ${q??1}${ar!=null?` · ${Number(ar).toFixed(2)} sq.ft`:''}`});} for(const p of photos as any[])a.push({key:`photo:${p.id}`,entityType:stage==='survey'?'survey_photo':'installation_photo',entityId:p.id,workItemId:p.work_item_id||undefined,title:stage==='survey'?(p.caption||'Survey Photo'):`Installation Photo${p.angle?` · ${p.angle}`:''}`,subtitle:p.work_item_id?'Mapped to measurement/work item':'Photo evidence',image:p.photo_url}); return a;},[items,photos,stage]);
 const dmap=useMemo(()=>new Map((decisions as any[]).map(d=>[`${d.entity_type}:${d.entity_id}`,d])),[decisions]);
 const toggle=(k:string)=>setSelected(s=>{const n=new Set(s);n.has(k)?n.delete(k):n.add(k);return n}); const selectAll=()=>setSelected(selected.size===rows.length?new Set():new Set(rows.map(r=>r.key)));
 async function apply(decision:'approved'|'redo') { if(!selected.size||!profile)return;setBusy(true);setErr('');try{const chosen=rows.filter(r=>selected.has(r.key));for(const r of chosen){const payload:any={organization_id:profile.organization_id,shop_id:shopId,stage,survey_id:surveyId||null,installation_job_id:jobId||null,entity_type:r.entityType,entity_id:r.entityId,decision,note:note||null,reviewed_by:profile.id,reviewed_at:new Date().toISOString()};const {error}=await supabase.from('field_review_decisions').upsert(payload,{onConflict:'stage,entity_type,entity_id'});if(error)throw error;if(decision==='redo'){
 const correction:any={organization_id:profile.organization_id,shop_id:shopId,stage,assigned_to:assignedTo||null,requested_by:profile.id,note:note||'Correction requested during evidence review',status:'open',survey_id:surveyId||null,installation_job_id:jobId||null,work_item_id:r.workItemId||null};
 if(r.entityType==='measurement')correction.issue_type='measurement'; if(r.entityType==='survey_photo'){correction.issue_type='survey_photo';correction.survey_photo_id=r.entityId;} if(r.entityType==='work_item')correction.issue_type='work_item'; if(r.entityType==='installation_photo'){correction.issue_type='installation_photo';correction.installation_proof_id=r.entityId;}
 await supabase.from('field_corrections').update({status:'cancelled'}).eq('stage',stage).eq(r.entityType==='survey_photo'?'survey_photo_id':r.entityType==='installation_photo'?'installation_proof_id':'work_item_id',r.entityId).eq('status','open'); const {error:ce}=await supabase.from('field_corrections').insert(correction);if(ce)throw ce;
 }} setSelected(new Set());setNote('');await qc.invalidateQueries({queryKey:['item-review-decisions']});await qc.invalidateQueries({queryKey:['field-corrections']});}catch(e:any){setErr(e.message||String(e));}finally{setBusy(false)}}
 return <div className="rounded-2xl border border-slate-200 bg-white overflow-hidden"><div className="px-4 py-3 bg-slate-50 border-b flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-slate-900">Item-by-item review</p><p className="text-xs text-slate-500">Approve or send only selected measurements/photos for redo — one-by-one or multiple together.</p></div>{!readOnly&&<button onClick={selectAll} className="text-xs font-medium text-blue-700 flex items-center gap-1">{selected.size===rows.length&&rows.length?<CheckSquare className="w-4 h-4"/>:<Square className="w-4 h-4"/>} Select all</button>}</div><div className="divide-y">{rows.map(r=>{const d:any=dmap.get(`${r.entityType}:${r.entityId}`);return <div key={r.key} className={`p-3 flex gap-3 ${d?.decision==='approved'?'bg-emerald-50/40':d?.decision==='redo'?'bg-amber-50/50':''}`}><button disabled={readOnly} onClick={()=>toggle(r.key)} className="pt-1">{selected.has(r.key)?<CheckSquare className="w-5 h-5 text-blue-600"/>:<Square className="w-5 h-5 text-slate-300"/>}</button>{r.image&&<img src={r.image} className="w-24 aspect-[4/3] object-contain bg-slate-100 rounded-lg border"/>}<div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><div><p className="text-sm font-semibold text-slate-900">{r.title}</p><p className="text-xs text-slate-500 mt-0.5">{r.subtitle}</p></div>{d&&<span className={`shrink-0 h-fit rounded-full px-2 py-1 text-[10px] font-bold ${d.decision==='approved'?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}>{d.decision==='approved'?'APPROVED':'REDO'}</span>}</div>{d?.note&&<p className="text-[11px] text-slate-500 mt-1">{d.note}</p>}</div></div>})}</div>{!readOnly&&<div className="p-3 border-t bg-slate-50 space-y-2"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional note for selected items (recommended for redo)" className="w-full rounded-lg border border-slate-300 px-3 py-2 text-xs"/><div className="grid grid-cols-2 gap-2"><button disabled={!selected.size||busy} onClick={()=>apply('approved')} className="rounded-lg bg-emerald-600 text-white py-2 text-sm font-semibold disabled:opacity-40 flex justify-center items-center gap-1"><CheckCircle2 className="w-4 h-4"/>Approve selected ({selected.size})</button><button disabled={!selected.size||busy} onClick={()=>apply('redo')} className="rounded-lg bg-amber-600 text-white py-2 text-sm font-semibold disabled:opacity-40 flex justify-center items-center gap-1"><RotateCcw className="w-4 h-4"/>Redo selected ({selected.size})</button></div>{err&&<p className="text-xs text-red-600">{err}</p>}</div>}</div>;
}
